# Generated by Django 2.2.8 on 2020-12-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Basliq')),
                ('slug', models.SlugField(max_length=110, verbose_name='Slug')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Dessert'), (2, 'Drink'), (3, 'Isti yemek'), (4, 'Sulu yemek')], verbose_name='Kategoriya')),
                ('short_description', models.CharField(max_length=255, verbose_name='Qisa Mezmun')),
                ('description', models.TextField(null=True, verbose_name='Mezmun')),
                ('image', models.ImageField(upload_to='media/recipe_images', verbose_name='Sekil')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
