# Generated by Django 2.2.8 on 2020-12-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Resept', 'verbose_name_plural': 'Reseptler'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mezmun'),
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='recipes',
        ),
    ]
