# Generated by Django 2.2.8 on 2020-12-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20201203_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-created_at', 'title'), 'verbose_name': 'Resept', 'verbose_name_plural': 'Reseptler'},
        ),
    ]
