# Generated by Django 2.2.8 on 2020-12-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20201222_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description_az',
            field=models.TextField(blank=True, null=True, verbose_name='Mezmun'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Mezmun'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_description_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Qisa Mezmun'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Qisa Mezmun'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_az',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Basliq'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_en',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Basliq'),
        ),
    ]
