# Generated by Django 2.2.8 on 2020-12-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201215_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(max_length=500, upload_to='', verbose_name='Image'),
        ),
    ]
