"""empty message

Revision ID: 368afb4fa4ed
Revises: 82a7329dd5a7
Create Date: 2021-01-12 10:14:42.246320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368afb4fa4ed'
down_revision = '82a7329dd5a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('category', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.add_column('category', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('recipe', 'image',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'image',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('category', 'updated_at')
    op.drop_column('category', 'is_published')
    op.drop_column('category', 'created_at')
    # ### end Alembic commands ###
