"""empty message

Revision ID: 82a7329dd5a7
Revises: e250b69effc1
Create Date: 2021-01-11 12:10:53.582159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a7329dd5a7'
down_revision = 'e250b69effc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.drop_table('recipe_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_tag',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name='recipe_tag_recipe_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='recipe_tag_tag_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recipe_tag_pkey')
    )
    op.drop_table('association')
    # ### end Alembic commands ###
